---
name: Set up Revopush management cli environment
author: Revopush
description: |-
  Downloads, installs, and configures a Revopush management CLI environment.
  Adds the `revopush` CLI command to the $PATH.
runs:
  using: node20
  main: build/setup/index.js
  post: build/setup-post/index.js
inputs:
  version:
    description: |-
      A string representing the version or version constraint of the Revopush CLI
      (`revopush`) to install (e.g. `"0.0.3"` or `">= 0.0.3"`). The default
      value is `"latest"`, which will always download and install the latest
      available Revpush CLI version.

          - uses: 'revopush/revopush-github-action@v1'
            with:
              version: '>= 0.0.3'
      
      If there is no installed `revopush` version that matches the given constraint, this GitHub Action will download and 
      install the latest available version that still matches the constraint.

      You are responsible for ensuring the `revopush` version matches the features required.
    default: 'latest'
    required: false
  accessKey:
    description: |-
      Revopush access key. Considered to be a secret.
      
         - uses: 'revopush/revopush-github-action@v1'
           with:
             accessKey:  <your Revopush access-key from GitHub secrets>
      
      You are responsible for ensuring the accessKey was not neither expired nor deleted by a user who created it.
    required: false
outputs:
  version:
    description: |-
      Version of revopush cli that was installed.
