on:
  workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tools cache
        id: tool-caches
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/revopush
          key: revopush-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            revopush-${{ runner.os }}-
      - name: Setup Revopush CLI
        uses: 'revopush/revopush-github-action@v1.0.0'
        id: setup-revopush-cli
        with:
          version: 'latest'
          accessKey: ${{ secrets.REVOPUSH_ACCESS_KEY }}
      - name: Release Android bundle
        run: revopush release-react myAmazingAndroidApp android -d Staging
      - name: Release ios bundle
        run: revopush release-react myAmazingIOSApp ios -d Staging
