on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test revopush cli
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tools cache
        id: tool-caches
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/revopush
          key: revopush-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            revopush-${{ runner.os }}-
      - name: Setup Revopush cli
        uses: ./ # Uses an action in the root directory
        id: revopush-cli
        with:
          version: '0.0.4'
          accessKey: ${{ secrets.REVOPUSH_ACCESS_KEY }}
      - name: List app
        run: revopush app ls

