name: 'Release'

on:
  workflow_dispatch:
    secrets:
      ACTIONS_BOT_TOKEN:
        required: true

jobs:
  release:
    if: "startsWith(github.event.head_commit.message, 'Release: v')"
    name: 'Release'
    uses: './.github/workflows/actions/release@main'
